# Local Zeebe Cluster
zeebe:
  client:
    broker:
      gateway-address: 127.0.0.1:26500
    message:
      timeToLive: P7D
    security:
      plaintext: true
    worker:
      max-jobs-active: 32
      threads: 2

#logging:
#  file:
#    path: ./logs           # specify a path to write to file, otherwise it defaults to the console.
#  level:
#    org.example.c8.basic.test: DEBUG

## Production Zeebe Cluster
#zeebe:
#  client:
#    cloud:
#      cluster-id:
#      client-id:
#      client-secret:
#      base-url: zeebe.camunda.io
#      port: 443
#      auth-url: https://login.cloud.camunda.io/oauth/token
#      region: bru-2
#    message:
#      timeToLive: P7D
#    worker:
#      max-jobs-active: 32
#      threads: 2